spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/products
        username: postgres
        password: 2004

jpa:
    show-sql: true
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update